name: DOCKER BUILD CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      name: deploy
      id: ref
      shell: bash
      with:
          node-version: ${{ matrix.node-version }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      run: npm i
      run: npm run build
      run: npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
 
     
